### ISSUE TITLE
ENOENT, no such file or directory

### ISSUE THREAD

**Issue by pdavid0** [shipitjs/shipit-deploy#1]
$ shipit staging rollback

    node.js:815
        var cwd = process.cwd();
                      ^
    Error: ENOENT, no such file or directory
        at Function.startup.resolveArgv0 (node.js:815:23)
        at startup (node.js:58:13)
        at node.js:906:3

Error message is kinda "blend".

**Comment by neoziro** [comment]
Maybe you are in a directory that doesn't exist yet?
