### ISSUE TITLE
pathspec 'master' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by sean-roberts** [shipitjs/shipit-deploy#102]
Ok so this is not actually an issue for me anymore but I wanted to post it here in case someone else runs into it.  I was getting the following error:

>
Checking out commit-ish "master"
Running "git checkout master" on local.
@ error: pathspec 'master' did not match any file(s) known to git.
>

and what was really causing it was the task before that ran this command:
>
Running "git fetch --depth=1 shipit -p --tags" on local.
>

the command did not create the actual .git/refs/heads/master as expected but put it in an unborn type of state. 
To resolve this all you needed to do was run another git fetch in that script. How I know this is, if you run `git remote show shipit` I got the following:

>
* remote shipit
  Fetch URL: {REPO_URL}
  Push  URL: {REPO_URL}
  HEAD branch: master
  Remote branch:
    master new (next fetch will store in remotes/shipit)
>

and running a git fetch again in the working directory added the master ref correctly.

ok so that helped me there in that state. But what REALLY solved my problem is that when realized my git wasn't doing something you guys were assuming it did, that my git version must be outdated. And it was. I was running 1.8.4. Since updating to 2.6.4, my shipit scripts worked immediately as intended.

That was a real pain to figure out for me. Hopefully that will help save someone else the time.

**Comment by handonam** [comment]
Yea, the documentation needs to be updated.  I saw "git 1.7.8+" as the local dependency and thought it was fine until I read this.  Thanks for the code aspirin!

**Comment by sean-roberts** [comment]
I agree, @neoziro git 1.7.8+ isn't exactly true
