### ISSUE TITLE
cp -a not available on non NTFS

### ISSUE THREAD

**Issue by bjoernsteinborn** [shipitjs/shipit-deploy#103]
tasks/deploy/update.js uses "cp" with the parameter "-a" which is only available on NTFS file systems.
(Source: https://www.mkssoftware.com/docs/man1/cp.1.asp)
So the copy task fails from OSX with HFS+.
Should/could be cp -r instead of cp -a.

**Comment by neoziro** [comment]
@bjoernsteinborn can you submit a PR please?

**Comment by bjoernsteinborn** [comment]
I will do so. At the moment i hardcoded the change for my needs but will look into making in configurable by parameter and than i create a PR out of it.

**Comment by bjoernsteinborn** [comment]
Solved with #107
