### ISSUE TITLE
Freeze on "updated" event

### ISSUE THREAD

**Issue by webdif** [shipitjs/shipit-deploy#104]
When deploying, my shipit often freeze after deploy, and broke my "updated" event handler as a result. Sadly, that's where I'm doing some crucial work (symlink to front-end).

What can I do? Any idea? I have no error message.
Thanks!

**Comment by neoziro** [comment]
I think it's relative to tasks you are doing in your code? Or your node version perhaps?

**Comment by webdif** [comment]
I'm creating folders and some symlinks, and doing some chmod / chown. My node is v5.0.0.
Is there anything I can do, other than ctrl+c when it freezes?

**Comment by webdif** [comment]
A screenshot, maybe it can help.
It freezes here:

![freeze-deploy](https://cloud.githubusercontent.com/assets/1285888/12757506/9a1e2084-c9d8-11e5-8665-36d6d5889f1d.png)

**Comment by neoziro** [comment]
Oh so it freezes at the end? You must have a connection to a database or something like that.
