### ISSUE TITLE
Deploy fails on v2.1.3

### ISSUE THREAD

**Issue by ddoonn** [shipitjs/shipit-deploy#108]
After upgrading to 2.1.3 cannot deploy fails with this
```

Running "git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"" on local.
@ From << MY REPO.GIT >>
@  * [new branch]      master     -> shipit/master
'deploy:fetch' errored after 2.41 s
Error: Command failed: /bin/sh -c git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
From << MY REPO.GIT >>
 * [new branch]      master     -> shipit/master
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

Deploy works fine at v2.0.0 because it runs

`Running "git fetch --depth=1 shipit -p" on local.`

I'm using gitlab so maybe it's a problem with the repo for that?

**Comment by pablocrivella** [comment]
+1 same issue here

**Comment by gabriel-rivero** [comment]
+1 same here

**Comment by traedamatic** [comment]
+1. Here too. Added a little catch function in fetch.js for a workaround

`javascript
function fetch() {
      var fetchCommand = 'git fetch' +
        (shipit.config.shallowClone ? ' --depth=1 ' : ' ') +
        'shipit --prune';
      // fetch branches and tags separate to be compatible with git versions < 1.9
      fetchCommand += ' && ' + fetchCommand + ' "refs/tags/*:refs/tags/*"';

      shipit.log('Fetching repository "%s"', shipit.config.repositoryUrl);

      return shipit.local(
        fetchCommand,
        {cwd: shipit.config.workspace}
      )
          .catch(function (e) {
            console.log(e);
          })
      .then(function () {
        shipit.log(chalk.green('Repository fetched.'));
      });
    }
`

**Comment by grEvenX** [comment]
+1, same issue here, `fetchCommand + ' "refs/tags/*:refs/tags/*"` returns exit-code `1` and makes the deploy fail.

**Comment by neoziro** [comment]
Probably relative to your version of git, try updating git, either feel free to make a PR

**Comment by grEvenX** [comment]
It only fails the command on some repos (not all) so I don't think it's the gut version itself. I will still try that and add a comment once that is tested

**Comment by neoziro** [comment]
@grEvenX OK, if you find the problem try to fix it in a PR and I will merge it. I do not use Shipit in my current developments (because no usecase for it).

**Comment by bjoernsteinborn** [comment]
It seems like it fails because of the combination of `"refs/tags/*:refs/tags/*"` and `--depth=1`. If you set `shallowClone: false` in the shipit config the `--depth=1` isn't added and everything works fine.

**Comment by Jokery** [comment]
+1 same here, deploy finished after adding any tag.

**Comment by benkaiser** [comment]
updating git to latest (2.7.3) fixed this

**Comment by simon-s9** [comment]
@benkaiser didn't work for me

```
$ git --version
git version 2.7.3
```

```
Error: Command failed: /bin/sh -c git fetch --depth=1 shipit --prune && git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"
```

**Comment by Jokery** [comment]
@simon-s9 try my solution, adding any tag.

**Comment by bjoernsteinborn** [comment]
#110 fixes the error, no hacks/tags whatever needed.
