### ISSUE TITLE
Why so slow?

### ISSUE THREAD

**Issue by thelinuxlich** [shipitjs/shipit-deploy#11]
I have a simple deploy which takes 16 minutes to complete. It just copies the directory, doesn't have any tasks

**Comment by neoziro** [comment]
@thelinuxlich because of your connection probably or the size of your project, you can try to install npm dependencies remotely instead of locally. Be careful of ignoring the ".git" directory.

**Comment by neoziro** [comment]
@thelinuxlich did you solve your problem?

**Comment by thelinuxlich** [comment]
It reduced the deployment time to 8 minutes. I still think it's very slow, when I was using git-deliver(https://github.com/arnoo/git-deliver/), I don't know why it was much faster.

**Comment by neoziro** [comment]
I don't know, but I gave you some leads, did it work?

**Comment by thelinuxlich** [comment]
Yeah, it reduced the deployment time in half

**Comment by neoziro** [comment]
I close it so...
