### ISSUE TITLE
Is there any way to deploy from the folder rather than a git url

### ISSUE THREAD

**Issue by pavankumarkatakam** [shipitjs/shipit-deploy#116]
I have a use case, that i build js porject using webpack and get the `dist/` folder . i want to upload to server  only `dist/` rather than the original code, so i checking the deployment tools that only deploy folder rather than a git repo url.

**Comment by timkelty** [comment]
Yep, you're looking for: https://github.com/shipitjs/shipit-deploy#dirtocopy

**Comment by akoenig** [comment]
We're facing the same use case and encountered a problem regarding the fact that `shipit-deploy` does not copy the files which are placed directly within the `dist/` directory.

```
dist/
   - JavaScript
   - Styles
   - index.html
```

The directories `JavaScript` and `Styles` will be transferred. The `index.html` does not. Is there any chance to modify the `cp` options?

Thanks :)

**Comment by pavankumarkatakam** [comment]
I have kept the '/dist' folder in config nd repository url is not given because I dont want to have access to git repo url. Now the error is

```
Fetching repository "undefined"
Running "git fetch shipit --prune --depth=1 && git fetch shipit --prune "refs/tags/*:refs/tags/*"" on local.
@ fatal: 'undefined' does not appear to be a git repository
@ fatal: Could not read from remote repository.
@ 
@ Please make sure you have the correct access rights
@ and the repository exists.

```

**Comment by feiin** [comment]
shipit-deploy was based on git , you should call build command with webpack after `deploy:fetch`,and then deploying from the output `/dist` folder.

**Comment by pavankumarkatakam** [comment]
ok, I understand it is fully git based, but is there is any hack to deploy local folder directly without git.

**Comment by timkelty** [comment]
Just don't use `shipit-deploy`.

Make your own one liner task using `shipit.remoteCopy`: https://github.com/shipitjs/shipit#shipitremotecopysrc-dest-options-callback

**Comment by pavankumarkatakam** [comment]
I thought it before when i see the Read me, but using that i will miss the rollback option right?

**Comment by pavankumarkatakam** [comment]
I thinking to give an idea, that if repositoryUrl is undefined in the init config just skip the below mentioned tasks

-  deploy:fetch
- Create workspace.
- Initialize repository.
- Add remote.
- Fetch repository.
- Checkout commit-ish.
- Merge remote branch in local branch.
- Emit event "fetched".
