### ISSUE TITLE
Error fetching if repo contains no tags

### ISSUE THREAD

**Issue by azatoth** [shipitjs/shipit-deploy#117]
If a repo contains no tags, then `git fetch --depth=1 shipit --prune "refs/tags/*:refs/tags/*"'` will return 1 and deployment halts.

**Comment by timkelty** [comment]
Good catch. Open to a PR, otherwise I should be able to take a look soon.

**Comment by neoziro** [comment]
https://github.com/shipitjs/shipit/issues/167
