### ISSUE TITLE
Arguments to rsync command not escaped?

### ISSUE THREAD

**Issue by robations** [shipitjs/shipit-deploy#120]
My deploy project path contains spaces (partly because Jenkins creates the directory with the project name), and this seems to cause a problem executing rsync to deploy:

```
Error: Command failed: /bin/sh -c rsync -az --del -e "ssh " /var/lib/jenkins/jobs/My Spaced Out Project/workspace/workspace/dist/ deploy@myserver:/var/www/deploy-location/staging/releases/20160123456789
rsync: link_stat "/var/lib/jenkins/jobs/My" failed: No such file or directory (2)
...
```

```
$ shipit --version
v1.4.1
```

**Comment by feiin** [comment]
using `'\\ '` instead of `' '` when setting workspace path.

like this:
`/var/lib/jenkins/jobs/My\\ Spaced\\ Out\\ Project/workspace/workspace/`

**Comment by robations** [comment]
The workspace path isn't specified in userland code, this is generated within shipit/shipit-deploy, presumably from the current working directory.

**Comment by feiin** [comment]
can you show me an example ?

**Comment by robations** [comment]
Hi, I tried to create a basic example here:

https://github.com/robations/test-shipit

To test this you'll need to do something like this:

```
mkdir "has space"
cd "has space"
git clone git@github.com:robations/test-shipit.git
cd test-shipit
# Now edit shipitfile.js and adjust testing/servers config to something you can access over ssh.
# Deploys to /tmp so should be safe to run on any dev box.
shipit testing deploy
```

You should then get an error that looks like:

```
Copy "/path/to/has space/test-shipit/workspace/" to "me@localhost:/tmp/releases/2016061609876" via rsync
@localhost-err rsync: link_stat "/path/to/has" failed: No such file or directory (2)
```

I'm testing this locally on OS X (with remote sharing switched on to enable sshd), but problem originally seen on Ubuntu 14.04, so I don't think it's OS dependent. Let me know if I've screwed up this example or if you need any more info!

**Comment by feiin** [comment]
@robations OK,I understand the problem. I will make a PR for this.

**Comment by feiin** [comment]
@robations OK,I understand the problem. the workspace should be another empty directory for shipit builds, should not set the root of your repository. like this:
```
module.exports = function (shipit) {
    require("shipit-deploy")(shipit);

    shipit.initConfig({
        default: {
            workspace: " /tmp/github.path.for.build",
            deployTo: "/tmp",
            repositoryUrl: "git@github.com:robations/test-shipit.git",
            keepReleases: 2,
            branch: "master"
        },
        testing: {
            servers: "username@localhost"
        }
    });
};
 
```

**Comment by robations** [comment]
@feiin That's not the problem, I specify a *subdirectory* from the project root as a relative path. If you specify a relative path to somewhere outside the root (but a path with spaces) there is still a problem.

So the real problem is that you cannot use relative paths if there is any chance that path will need escaping, this could be caused by a spcae, by a `$` sign, and so on. If this is the case why is `path.resolve` used here?

https://github.com/shipitjs/shipit-deploy/blob/e637e5efd7b6d5d833813ed1b2dc247d0142ea01/tasks/deploy/update.js#L69

Would you take a pull request for this as a new feature? I think this would be a useful improvement because many people use subdirectories for creating builds etc. and if running on different servers it is not good to make assumptions about the filesystem by setting an absolute path.

Personally, I think this should be handled by `ssh-pool` but I see they have already rejected this as a bug, saying that path escaping should be handled externally: https://github.com/shipitjs/ssh-pool/issues/13

**Comment by robations** [comment]
Okay... I see `path.resolve` is used to resolve the "dirToCopy" not the "workspace" path. Still, I think this would be a useful "feature" to support relative paths.

**Comment by neoziro** [comment]
If still a problem, please reopen an issue on [shipit repository](https://github.com/shipitjs/shipit)
