### ISSUE TITLE
SSH Key issue

### ISSUE THREAD

**Issue by romeoordos** [shipitjs/shipit-deploy#126]
It seems that deploy task completely ignores 'key' configuration field.  I had to create addSshKey function between 'createWorkspace' and 'initRepository' to make it work.

> function addSshKey() {
>       if (!shipit.config.key) {
>         return Promise.resolve();
>       }
>       shipit.log('Add SSH key "%s" to SSH-Agent', shipit.config.key);
>       return shipit.local('ssh-add ' + shipit.config.key, {cwd: shipit.config.workspace})
>       .then(function () {
>         shipit.log(chalk.green('SSH key added'));
>       });
> }

**Comment by dklanac** [comment]
@romeoordos I'm not terribly familiar with ShipIt. Could you point me to where I would paste your workaround code to get ShipIt to recognize my SSH key?

**Comment by neoziro** [comment]
```js
shipit.blTask('addSshKey', async function addSshKey() {
  if (!shipit.config.key) return
  shipit.log('Add SSH key "%s" to SSH-Agent', shipit.config.key);
  await shipit.local(`ssh-add ${shipit.config.key}`, { cwd: shipit.config.workspace })
  shipit.log('SSH key added')
})

shipit.on('deploy', () => {
  shipit.start('addSshKey')
})
```

@romeoordos try this

**Comment by dklanac** [comment]
Awesome! Thanks so much @neoziro

**Comment by neoziro** [comment]
@dklanac is it working?

**Comment by dklanac** [comment]
I couldn't get it to work just now when I tried it. I was able to see the logged "Add SSH key..." output when it ran, but I continued to be prompted to enter my github user/pass. I'm in a time crunch, so I opted for capistrano and got it running with my key. Thanks for your help though.

**Comment by neoziro** [comment]
@dklanac OK sorry for that, will be good in v4.

**Comment by aviramga** [comment]
@neoziro Im also trying to use this workaround and getting:
Error: Command failed: ssh-add <path-to-rsa>
Could not open a connection to your authentication agent.

**Comment by aviramga** [comment]
For whom it may concern, I found a much simpler solution:
add this to your shipitfile config

      gitConfig: {'core.sshCommand':"ssh -i <path-to-you-rsa-key>"}

Requires git >2.10 to work

**Comment by neoziro** [comment]
Will be fixed in v4 https://github.com/shipitjs/shipit/issues/156
