### ISSUE TITLE
[FR] Be able to configure 'releases' and 'current' directory names

### ISSUE THREAD

**Issue by adamj88** [shipitjs/shipit-deploy#128]
At the moment the 'releases' and 'current' directories are hard coded.

Would it be possible for them to be controlled by using `shipit.config`?

The following seem to be where they occur:

https://github.com/shipitjs/shipit-deploy/blob/master/lib/init.js#L5-L6
https://github.com/shipitjs/shipit-deploy/blob/master/tasks/deploy/publish.js#L28-L30

**Comment by rdewolff** [comment]
I would love seeing that option too.

**Comment by timkelty** [comment]
Sounds like a good config.
I'll get around to it when I have time, otherwise - always open to a PR.

**Comment by adamj88** [comment]
Furthermore to this, it would be good to be able to override the `shipit.releaseDirname`.

My use case is builds which get deployed are compiled as part of a pipeline with it's own ID number. It would be easier to reference this to be able to backtrace to the deployment stage rather than a date/time.

I attempted the previously mentioned points, but wasn't able to see how to convert these to configurable options.

**Comment by neoziro** [comment]
I disagree, I want to keep Shipit opinionated (even more than before). I suggest you to build your own deploy task instead of using shipit-deploy if you want this kind of feature.
