### ISSUE TITLE
Path to latest release directory before update of `current`

### ISSUE THREAD

**Issue by paulmenzel** [shipitjs/shipit-deploy#13]
Hi. With shipit-deploy 1.1.1, we want to run an `deploy:install` task running `npm install` after the `updated` event has been emitted, that means before the symbolic link `current` is updated, so

    var current = grunt.config('shipit.options.deployTo') + '/current';

does not work.

As that needs to be run from the latest release directory, how can that be figured out?

As a work-around, we run the `deploy:install` task after the publication of the `published` event.

**Comment by neoziro** [comment]
@paulmenzel hi, first sorry for answering 14 days later..

I think you can use `shipit.releasePath` variable to achieve that.
