### ISSUE TITLE
Password prompt during deploy on OSX

### ISSUE THREAD

**Issue by AndreaStevanato** [shipitjs/shipit-deploy#133]
Hi, 

I have setted the SSH public-key on the server but during the deploy still ask me the password for every command. This problem occurs only on OSX when i run `shipit test deploy`, if I run from terminal `ssh  -t user@server "cd /opt/deploy && ls"` do not ask me for password.

On Ubuntu with the same `shipfile` works fine.

Prompt password:
```
Running 'deploy:update' task...
Running "if [ -h /opt/deploy/current ]; then readlink /opt/deploy/current; fi" on host "server".
user@server's password:
```

**Comment by timkelty** [comment]
Hmmm. Doesn't make a whole lot of sense to me unfortunately.

You could try `ssh-copy-id user@server` just to make sure the key is copied correctly.
Other than that, I'm not sure why node executing the command would lost the key.

**Comment by AndreaStevanato** [comment]
it ask me the password only for shipit commands.

**Comment by AndreaStevanato** [comment]
Resolved! The problem was the ssh key's path.

**Comment by timkelty** [comment]
Glad you figured it out! 💯
