### ISSUE TITLE
Cache workspace option

### ISSUE THREAD

**Issue by tsugitta** [shipitjs/shipit-deploy#134]
in my JavaScript project, every time I deploy, there are git pulling and installing all npm packages.
I wanna avoid it as it takes a lot of time.

If it is possible to save workspace dir (or don't clean workspace dir), faster deployment can be done.

**Comment by timkelty** [comment]
See the https://github.com/shipitjs/shipit-deploy#shallowclone option to speed up fetching.

If you have this set the workspace will need to be cleaned each time, but the fetching process may be shorter. Without it, workspace is not cleaned.

**Comment by diggy** [comment]
You can also symlink your node_modules, vendor, ... dirs to speed things up, e.g. (w/ grunt-shipit):

```
shipitUtils.registerTask(grunt, 'symlink_node_modules', function() {
    var workspace = grunt.config('secret.shipit.workspace');
    return grunt.shipit.local('cd ' + workspace + ' && ln -s ' + path.resolve() + '/node_modules node_modules');
});

grunt.shipit.on('fetched', function () {
    shipitUtils.runTask(grunt, ['symlink_node_modules']);
});
```

**Comment by tsugitta** [comment]
thanks for great answers!
