### ISSUE TITLE
Deployment does not delete files properly if Rsync is not available

### ISSUE THREAD

**Issue by zookatron** [shipitjs/shipit-deploy#137]
There seems to be an issue with shipit not properly removing deleted files if rsync is not available during deployment. The 'deploy:update' task copies the files from the previous revision over to the new deployment directory in order to make rsync faster, but it doesn't detect if rsync is actually available when it does this. Then, when it gets to the actual file transfer process, it will fall back to tarring the new files, sending them over scp, and untarring them on the server, but this doesn't delete any files that were removed by the new revision like rsync does. It seems like the easiest solution to this would be to have the 'deploy:update' task check for rsync being available before it does the performance-enhance copy.

**Comment by moacirosa** [comment]
I'm facing some similar issues but I'm not sure what you mean by "not available". Reading [`shipit` documentation](https://github.com/shipitjs/shipit#dependencies) `rsync` is currently listed as a dependency. So maybe "not being available" is not an option.

**Comment by zookatron** [comment]
> rsync is currently listed as a dependency. So maybe "not being available" is not an option.

Even though it is listed as a "dependency", shipit explicitly checks for the existence of rsync and falls back to tarring and scping the files in it's absence instead of simply displaying an error, which seems to indicate that it is intended to support systems without rsync? If not, it should simply display an error and quit if it can't find rsync.

**Comment by timkelty** [comment]
Open to a PR.
