### ISSUE TITLE
What is the preferred way to install dependencies ?

### ISSUE THREAD

**Issue by faressoft** [shipitjs/shipit-deploy#141]
What is the preferred way to install dependencies like using `npm install` and `bower install`. Should I do that after the `deployed` event is fired ? What if the installation is failed for some reason ! What should I do in this case ? Is there anyway to not execute the task `deploy:publish` before installing the dependencies !

**Comment by timkelty** [comment]
You can use https://github.com/callerc1/shipit-npm for installing npm packages.

Or - if you do it yourself, you should use the `updated` event.
This way if it fails, the deploy will be halted.
