### ISSUE TITLE
remoteCopy invalid path due to posix

### ISSUE THREAD

**Issue by wubzz** [shipitjs/shipit-deploy#146]
Hi,

I'm running `shipit ` with `shipit-deploy` on a windows environment trying to supply the path for `workspace` to a secondary disk (storage) as such:
`{workspace: 'E:/tmp/projectname'}`

Everything goes well until `shipit-deploy` reaches `remoteCopy` where it tries to resolve the local path: https://github.com/shipitjs/shipit-deploy/blob/master/tasks/deploy/update.js#L71

Since the entire repository seems to force posix, this results in the path resolving from `E:/tmp/projectname` -> `/E:/tmp/projectname` which is invalid and the upload procedure naturally fails.

I couldn't find any similar issues in the repo. Is there a workaround of sorts?

Why is posix forced btw? Couldn't really figure out a reason.

**Comment by wubzz** [comment]
Workaround in my case: Supply `/tmp/projectname` instead as it defaulted to `E:/` drive (from `process.cwd()`). 

Totally a downer that just this one single row in the repository uses this rule while other tasks succeed. To make it cross-platform compatible it would make more sense to instead force the user of the lib to supply the resolved path, don't see why it falls on shipit-deploy to take care of it.

**Comment by wubzz** [comment]
Got caught on this once more. Reopening in hopes that this gets looked at.

**Comment by neoziro** [comment]
This repository will be archived, v4 is coming. Please feel free to reopen this issue in [main repository](https://github.com/shipitjs/shipit) if you experienced the problem in v4.
