### ISSUE TITLE
bashism in updateSymbolicLink

### ISSUE THREAD

**Issue by nkovacs** [shipitjs/shipit-deploy#147]
This is a bashism: https://github.com/shipitjs/shipit-deploy/commit/f47470e8bf82f1a0566a1b1e6a61f7147c5c6068

You should instead use `if [ -d current ] && ! [ -L current ];` so that it works on all posix shells.

**Comment by pgsimon** [comment]
+1

**Comment by neoziro** [comment]
@nkovacs thanks, open to PR

**Comment by neoziro** [comment]
https://github.com/shipitjs/shipit/issues/156
