### ISSUE TITLE
How do we abort releases when the remote npm install fails? 

### ISSUE THREAD

**Issue by glade-at-gigwell** [shipitjs/shipit-deploy#149]
We're adopting a project that uses shipit-deploy, and one thing we've found is that new builds will continue deploying even though the remote npm install fails (for various setup reasons)

Can we abort/rollback the release on remote npm install fail? 

Thanks!

**Comment by neoziro** [comment]
@glade-at-gigwell yes, why not using "npm install || true"?

**Comment by neoziro** [comment]
@glade-at-gigwell problem solved?
