### ISSUE TITLE
Ignores SSH key config

### ISSUE THREAD

**Issue by dklanac** [shipitjs/shipit-deploy#151]
I've referenced my SSH key in my config that I use for authenticating to my server. 
```
shipit.initConfig({
    default: {
    key: '~/.ssh/id_rsa'
    ...

```
Capistrano is able to use this key just fine for my Rails app. But ShipIt seems to ignore it. I saw a similar issue with a proposed workaround (#126), but I'm not clear on how to use it. 

I'm running macOS 10.12, node 8.2 and shipit-deploy 2.5.1 if that makes a difference.

Any ideas (other than the path which I've verified) why ShipIt would ignore my SSH key?

**Comment by neoziro** [comment]
@dklanac hmm it's a bug should be fixed in v4, I gived you a workaround in https://github.com/shipitjs/shipit-deploy/issues/126

**Comment by aviramga** [comment]
@neoziro when will V4 be out?

**Comment by neoziro** [comment]
@aviramga as soon as possible, I have a lot of work I need a day of two off to finish v4.

**Comment by aviramga** [comment]
@neoziro here is a workaround
add this to your shipitfile config

      gitConfig: {'core.sshCommand':"ssh -i <path-to-you-rsa-key>"}

Requires git >2.10 to work

**Comment by neoziro** [comment]
Will be solved in v4.

**Comment by neoziro** [comment]
https://github.com/shipitjs/shipit/issues/156
