### ISSUE TITLE
May be add `verbosity` level like [ v | vv | vvv ] ?

### ISSUE THREAD

**Issue by tebaly** [shipitjs/shipit-deploy#152]
Deployer - is for deploy in PHP like capistrano, like shipit(like capistrano). My proposal is:

![image](https://cdn-images-1.medium.com/max/1200/1*66Tm-wXmrzcwPX9yre5x1A.gif)

`-v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug`

Other comands - https://deployer.org/docs/cli

**Comment by neoziro** [comment]
Yes good idea.

**Comment by neoziro** [comment]
https://github.com/shipitjs/shipit/issues/166

**Comment by tebaly** [comment]
What is the hidden meaning in this movement :jack_o_lantern:
