### ISSUE TITLE
May be add `default` environment|stage?

### ISSUE THREAD

**Issue by tebaly** [shipitjs/shipit-deploy#153]
To be able to make
`shipit deploy`  

For example on Deployer (PHP) i can execute one comand _dep deploy_ (deploy - is task)

**Comment by neoziro** [comment]
Bad idea, I prefer the environment to be explicit.

**Comment by timkelty** [comment]
@tebaly I initially wanted your request as well, but now tend to agree with @neoziro.

With a default environment, I found myself wanting a verification prompt, for the target env, which can be simplified by just requiring it as part of the command.

If you really can't stand typing it, I would suggest a shell alias or an npm script command, or something similar.

**Comment by timkelty** [comment]
@neoziro one thing I would consider:
When no environment is provided, we could display an inquirer.js select prompt with available environments.

**Comment by neoziro** [comment]
Yes we can consider it, but it is not a priority for now. I think typing the name of the environment is not a lot and it prevents mistakes.

**Comment by neoziro** [comment]
@tebaly I keep the idea, will not be part of Shipit v4, but maybe next release!
