### ISSUE TITLE
Deploy fails because `mv -T` is illegal option

### ISSUE THREAD

**Issue by mmiszy** [shipitjs/shipit-deploy#158]
```
'deploy:publish' errored after 553 ms
Error: Command failed: ssh user@server "cd /usr/home/…/nodejs && if [[ -d current && ! (-L current) ]]; then echo \"ERR: could not make symlink\"; else ln -nfs releases/20171204175536 current_tmp && mv -fT current_tmp current; fi"
mv: illegal option -- T
usage: mv [-f | -i | -n] [-hv] source target
       mv [-f | -i | -n] [-v] source ... directory
```

**Comment by pbgms** [comment]
Same.
@mmiszy did you solve this?

**Comment by mmiszy** [comment]
Nope. I decided to write a bash script instead.

**Comment by cquinders** [comment]
I just encountered this issue with a FreeBSD 10.3 remote server. If I remove the `-T` option it works as expected.

Is there any downside to changing the command to this:
```
mv -f current_tmp current
```

**Comment by neoziro** [comment]
This repository will be archived, v4 is coming. Please feel free to reopen this issue in [main repository](https://github.com/shipitjs/shipit) if you experienced the problem in v4.
