### ISSUE TITLE
Deploy:update fails to load lib/shipit

### ISSUE THREAD

**Issue by GabeAtWork** [shipitjs/shipit-deploy#159]
I'm having trouble with auto-deploying from jenkins setup on CentOS 7, running with node `8.9.3` and yarn `1.3.2` (shipit-deploy v. `2.5.1`).

The deploy works as expected until `deploy:update`, where I get the following error:

```
Running 'deploy:update' task...
'deploy:update' errored after 294 μs
Error: Cannot find module '../../lib/shipit'
```

The reference file line is `node_modules/shipit-deploy/tasks/deploy/update.js:24:44`, which does the require. I indeed don't see the classic `module.exports = {}` in `shipit.js`.

That being said, on my local it works fine, running with MacOS. I'm puzzled by this error, does anyone have a fix?

**Comment by neoziro** [comment]
It looks very weird, and should be solved in v4. I don't have time to test it deeply but if you have any update, I am interested.

**Comment by neoziro** [comment]
This repository will be archived, v4 is coming. Please feel free to reopen this issue in [main repository](https://github.com/shipitjs/shipit) if you experienced the problem in v4.
