### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by callerc1** [shipitjs/shipit-deploy#16]
Im having an issue when using shititjs to deploy to a vagrant VM. 

Im using the same identity file that is set in my `~/.ssh/config` which i use to connect to my VM.
 
`key: '~/.vagrant/machines/default/virtualbox/private_key'`

```
Error: Command failed: Permission denied (publickey,password).

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:117:20)
    at Pipe.close (net.js:465:12)
```

**Comment by callerc1** [comment]
i am also sometimes getting this error: 

`Error: Command failed: Warning: Identity file ~/.vagrant/machines/default/virtualbox/private_key not accessible: No such file or directory.`

**Comment by neoziro** [comment]
@callerc1 I think it's a problem of permission of your key, I don't use vagrant but your problem is not relative to Shipit.. Try to check the permission of your key compared to the user you use to deploy.

**Comment by callerc1** [comment]
@neoziro Thanks. Yes i opened up all the permissions on the key as a test and still the same problem.

**Comment by callerc1** [comment]
if i remove the key option entirely it still throws this error:
```
Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:117:20)
    at Pipe.close (net.js:465:12)
```

**Comment by neoziro** [comment]
@callerc1 I am sorry but I don't know what's going wrong

**Comment by callerc1** [comment]
@neoziro can i just confirm that the key should be the private key to use on your local machine that is running the deploy?

**Comment by neoziro** [comment]
@callerc1 yes, in ssh you have a private key and a public key, the public key must be on the remote server and the private key on your machine.

**Comment by callerc1** [comment]
diving in a little deeper looks like it was an issue with rsync... reinstalled it. now it works. No need to specifying a key as i let my `~/.ssh/config` take care of that.
