### ISSUE TITLE
Doing tasks with a different user or than the login one

### ISSUE THREAD

**Issue by masterkorp** [shipitjs/shipit-deploy#17]
Hello, 

First of of all this tools looks awesome, congratulations :+1: 

I would like to perform my tasks with an user different than the one I login into the servers.
Can you shed some light on how to do this ?

Regards,
Alfredo Palhares

**Comment by neoziro** [comment]
You can wrap command with "sudo -u youruser".

**Comment by masterkorp** [comment]
@neoziro thanks, how do I do that on shippit without rewriting all the tasks ?

**Comment by neoziro** [comment]
@masterkorp you will have to rewrite all tasks, but just create a method that wrap the command, it will be less painful
