### ISSUE TITLE
An idea that can improve deployment speed

### ISSUE THREAD

**Issue by oliverzy** [shipitjs/shipit-deploy#19]
Hi,

I would like to say the module is awesome, thanks.

The problem I find is that since it will create a new release folder on the server every time, it will have to copy everything from local to server even if the local and remote has only minimal changes.

Since rsync can do a pretty good job to figure out what has been changed between local and remote, I think maybe it's a good idea to create a copy of previous release on the server rather than simply mkdir on the server.

Maybe this can be an another option so that the user can decide.
What do you think?

**Comment by oliverzy** [comment]
See https://github.com/shipitjs/shipit-deploy/pull/20

**Comment by neoziro** [comment]
@oliverzy good idea, I will comment your PR.

**Comment by tinchoz49** [comment]
great idea oliverzy! :+1:
