### ISSUE TITLE
Add an option to delete a 'faulty' deployment after a rollback?

### ISSUE THREAD

**Issue by mkuster** [shipitjs/shipit-deploy#22]
We use this tool since some days for our deployments. Today I had to do my first rollback (no problem) and then my second: And I was confused for some minutes..

Reason: Rollback is currently to the previous deployment in time, and not the previous "stable" one. 
Example:
- Deployment A is stable and deployed.
- I deploy B - doesn't work - I do rollback -> rollback to A => deployment fixed
- Devs try to fix..
- I deploy C - still doesn't work - I do rollback -> rollback to B => deployment still broken

After reading the code, I understand why this happens and I don't think that there is a easy way to mark a deployment as stable.
But, what do you think about an option to delete a deployment from the remote servers, when there is a rollback? (Should be rather easy, as the rollback code already knows from which deployment we rollback)

In my example, this would delete B after rollback to A, so that a rollback from C would also roll back to A..

**Comment by mkuster** [comment]
Or, if you want to analyze it later why it's broken, rename the faulty release to something special..

**Comment by neoziro** [comment]
@mkuster I understand your problem, maybe deleting the previous release is a good solution. If we rename it, it will be confusing in sorting etc..

**Comment by ryantemple** [comment]
I've had a go at this in #67 as it looks a useful thing to have  Let me know what you think.
