### ISSUE TITLE
Will fail silently if `current` already exists

### ISSUE THREAD

**Issue by yamadapc** [shipitjs/shipit-deploy#29]
If the server has a directory `current` at `shipit.releaseDirname`, `deploy/publish` will fail silently. Instead of correctly replacing a `current` symlink with the new one, it'll symlink the release inside of the old `current` directory.

Ideally, IMO, [`updateSymbolicLink`](https://github.com/shipitjs/shipit-deploy/blob/f94f063320d5470d8d0202069d4d2786c2d36110/tasks/deploy/publish.js#L25-L34) would be modified to make sure the directory doesn't exist and fail if it does.

Something along the lines of:

``` javascript
function updateSymbolicLink() {
  shipit.log('Publishing release "%s"', shipit.releasePath);

  var relativeReleasePath = path.join('releases', shipit.releaseDirname);

  return shipit.remote(
    'cd ' + shipit.config.deployTo + ' && ' +
    'if [[ -d target && ! (-L target) ]]; then ' +
    'echo nack; ' +
    'else ' +
    'ln -nfs ' + relativeReleasePath + ' current && echo ack;' +
    'fi'
  )
  .then(function (results) {
    var failedResults = results.filter(function(r) {
      return r.stdout !== 'ack'; // Or something
    });
    if(failedResults.length) {
      // Throw that the deployment failed telling what servers and why; IDK
    }

    shipit.log(chalk.green('Release published.'));
  });
}
```

**Comment by neoziro** [comment]
@yamadapc OK I understand the problem, but I think it's an edge case and it's a requirement to have your server clean before deploying. So I think we need not to address this problem. If some else get it why not, but let's see before doing something.

**Comment by kirstein** [comment]
Failing silently is still a bad way to handle that situation. It should at least notify the user.

**Comment by neoziro** [comment]
@kirstein yes, agreed. So can you make a PR for that please?
