### ISSUE TITLE
Getting following error ssh command

### ISSUE THREAD

**Issue by thetutlage** [shipitjs/shipit-deploy#34]
`Unhandled rejection Error: Command failed: /bin/sh -c ssh root@xx.xxx.xx.xxx "readlink /root/nodeapps/ship/current"`

**Comment by neoziro** [comment]
@thetutlage did you install [dependencies](https://github.com/shipitjs/shipit-deploy#local)?

**Comment by thetutlage** [comment]
Yes i have following installed

`rsync 3.1.1`
`git 1.9.5`

**Comment by tlartaud** [comment]
Same error here.
I've just updated from 1.1.1 to 1.2.0.

Some test commands :

On a fresh deploying environment where the `current` symlink does not exist yet
```
[10:28 AM]-[vagrant@thomastage]-[/var/www/domain.dev]-[git develop]
$ ssh deploy@test.domain.com "readlink /test.domain.com"
```

However, it works if current symlink exists :-1: 
```
[10:28 AM]-[vagrant@thomastage]-[/var/www/domain.dev]-[git develop]
$ ssh deploy@test.domain.com "readlink /staging.domain.com/current"
releases/20150323170315
```

Maybe that you should check for symlink existence before using `readlink` ?

Thanks.
