### ISSUE TITLE
Releases nested within current folder

### ISSUE THREAD

**Issue by scottzirkel** [shipitjs/shipit-deploy#40]
Currently when I deploy, I am getting a folder within the current release which also has a release folder within it. I think it is happening during the deploy:update task.

After a few more deploys, I see that there are several folders of prior releases nested within the current folder.

**Comment by dr-impossible** [comment]
I'm experiencing the same problem as well. Version 1.2 does not have this issue.

**Comment by timkelty** [comment]
Are you running rsync 3?
`rsync --version`

**Comment by scottzirkel** [comment]
Nope, I have 2.6.9. Just updated to 3.1.0 and it's still doing it.

**Comment by timkelty** [comment]
Ok, I'll check it out then - can you post any other info about your environment?

BTW - Shipit states that rsync 3 is a dependency: https://github.com/shipitjs/shipit

**Comment by scottzirkel** [comment]
Totally missed it, thanks.

What environment info would help you?

**Comment by timkelty** [comment]
Mac or PC?

**Comment by scottzirkel** [comment]
Mac running Mavericks with the latest updates.

**Comment by timkelty** [comment]
Thanks, I'll take a look in a few minutes.

**Comment by timkelty** [comment]
@scottzirkel @dr-impossible fixed here: https://github.com/shipitjs/shipit-deploy/pull/44
Thanks for catching this!
