### ISSUE TITLE
Fail on deploy:update with branch config set

### ISSUE THREAD

**Issue by scottzirkel** [shipitjs/shipit-deploy#47]
When deploying from a specified git branch, I get the following error:
```
Release path created.
Setting current revision and creating revision file.
Running "git rev-parse BRANCH" on local.
@ fatal: ambiguous argument 'BRANCH': unknown revision or path not in the working tree.
```

Obviously BRANCH is the place holder for my branch name.
I remove the branch option from the initConfig and it works fine.

**Comment by neoziro** [comment]
I don't understand your problem. Can you give more details please?

**Comment by scottzirkel** [comment]
When I specify a branch in the config, I get the above error. If I remove the branch attribute it pulls from master and works fine. I just wanted it to pull from a different repo branch.

**Comment by neoziro** [comment]
@scottzirkel can you copy your config please?

**Comment by scottzirkel** [comment]
```
shipit.initConfig({
    default: {
    workspace: workspace,
    repositoryUrl: repoUrl,
    branch: 'shipit',
    ignores: ['.git', 'node_modules'],
    keepReleases: 2
   }
  });
```

**Comment by neoziro** [comment]
@scottzirkel I don't know how it's possible, there is no "BRANCH" string in the code.

**Comment by scottzirkel** [comment]
Maybe I'm reading it wrong, but branch is one of the options listed in the readme.

### branch

Type: `String`

Tag, branch or commit to deploy.

**Comment by neoziro** [comment]
@scottzirkel yes what you do is correct, I don't know why you get this error message.

**Comment by scottzirkel** [comment]
Oh, BRANCH in the first code was my branch name. I just renamed it BRANCH for readability. Sorry.

**Comment by neoziro** [comment]
I think your branch is not on the origin.

**Comment by scottzirkel** [comment]
Hmm... It's listed in the origin when I run `git remote show origin`. I'll play with it more on my end to see if I can't get it to work.

**Comment by scottzirkel** [comment]
I ran it again and it is cloning the correct repo, it was failing because of some custom scripts I have that cleans up the directory. I was deleting the non-build files which included the .git folder. It was on my end, sorry for the trouble.

**Comment by neoziro** [comment]
@scottzirkel OK cool
