### ISSUE TITLE
Fetch should not delete the workspace folder

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit-deploy#5]
Currently, if you have `shallowClone: true`, on every deploy the workspace gets wiped: https://github.com/shipitjs/shipit-deploy/blob/master/tasks/deploy/fetch.js#L43-L47

This can result in _really_ slow deploys, especially if you have alot of things to build on deploy.

**Comment by neoziro** [comment]
@timkelty yes it's an optimization. It's complicated to address, I think that for node, we need a dedicated deploy tasks that cache npm packages (and bower packages). We should inspire by heroku buildpacks. I don't have time do work on this. If someone is interested, let me know.

**Comment by timkelty** [comment]
I may look into it.
I was going look at precisely what Capistrano does, but yeah npm packages are a problem.

**Comment by neoziro** [comment]
@timkelty I don't want to do like Capistrano, I think we need a specific deploy task for each type of project.

**Comment by neoziro** [comment]
@timkelty without shallowClone, you don't have this problem.
