### ISSUE TITLE
pause deployment until event listeners are handled

### ISSUE THREAD

**Issue by alubbe** [shipitjs/shipit-deploy#54]
Is it possible to pause deployment until event listeners are handled?

Specifically, this code
```js
shipit.on('updated', function() {
  return shipit.remote("cd " + shipit.releasePath + " && " + NPM_BIN + " install");
});
```
will run concurrent with the publish and clean tasks. Instead, I would like it to wait until npm install is done and then publish & clean.

**Comment by alubbe** [comment]
I think I might have figured it out. The trick seems to wrap the remote call in a blocking named task like this:
```js
shipit.blTask('npm install', function() {
  return shipit.remote("cd " + shipit.releasePath + " && " + NPM_BIN + " install");
});

shipit.on('updated', function() {
  return shipit.start('npm install');
});
```
Is this the correct idiomatic way to use this module?

**Comment by neoziro** [comment]
@alubbe yes you must wrap it in a task, and orchestrator will do it for you, it's always a good practice to wrap it in a task.
