### ISSUE TITLE
An event for when a error occurs

### ISSUE THREAD

**Issue by thelinuxlich** [shipitjs/shipit-deploy#6]
It would be very useful

**Comment by neoziro** [comment]
Shipit inherits from [orchestrator](https://github.com/orchestrator/orchestrator) so you can listen every orchestrator events (including errors).

**Comment by weotch** [comment]
If that's the case, shouldn't this work? (it's not)

```js
shipit.on('err', function() {
  return console.log('I died');
});
```

I am forcing a task error by running `npm installzz` from a task.

**Comment by judewang** [comment]
I do have the same problem. Neither listening to 'err' or 'task_err', the callback won't run.
