### ISSUE TITLE
Deploy different branch for different environment

### ISSUE THREAD

**Issue by tsturzl** [shipitjs/shipit-deploy#60]
I have shitit set up using grunt-shipit to deploy to staging. However I cannot figure out how to change the branch for a different shipit environment. I have a different branch to merge staging and production, however I only see docs for defining a single branch for all deployment environments. Is it possible to change the branch for different environments?

It would be really nice to do something like this:

```
module.exports = function (grunt) {
    grunt.initConfig({
        shipit: {
            options: {
                workspace: '/tmp/deploy',
                deployTo: '/project/deploy',
                repositoryUrl: 'https://github.com/******',
                ignores: ['.git', 'docs', 'docs_build', 'tests'],
                keepReleases: 3,
                shallowClone: true
            },
            staging: {
                servers: ['node@***.***.***.***'],
                branch: "staging"
            },
            production: {
                servers: ['node@***.***.***.***']
                branch: "production"
            }
        }
    });

    grunt.loadNpmTasks('grunt-shipit');
    grunt.loadNpmTasks('shipit-deploy');

};
```

**Comment by neoziro** [comment]
@tsturzl you can use a module like [optimist](https://github.com/substack/node-optimist) to be able to specify a custom branch

**Comment by tsturzl** [comment]
I suppose I was looking for a gruntful way of doing things, but parsing `process.argv` works. I just parse `process.argv[2].match(/staging/g)` and set the branch that way.

**Comment by neoziro** [comment]
@tsturzl yes it's your choice

**Comment by briantbutton** [comment]
@tsturzl thanks for writing back to describe your workaround.  Saved me a lot of time!
