### ISSUE TITLE
I dont want to merge with previous release, how to do this?

### ISSUE THREAD

**Issue by fundon** [shipitjs/shipit-deploy#64]
I found an issue.

Some files was removed/changed in source repo. But when I updated it, they were recoverd and used the previouse release.

This confuse me.

**Comment by neoziro** [comment]
Yeah, it's an optimization, we take the previous release and we make a rsync to prevent uploading all of sources each time. What is your problem?

**Comment by neoziro** [comment]
@timkelty maybe we could do this optionally?

**Comment by fundon** [comment]
@neoziro Below is an example:

e.g.

previous release
```
<script src="1.js"/>
<script src="2.js"/>
<script src="3.js"/>
```

In latest version

```
<script src="1.js"/>
<script src="3.js"/>
```

If delopy the latest release, previous lease will merge to the latest version, so result is:

```
<script src="1.js"/>
<script src="2.js"/>
<script src="3.js"/>
```

**Comment by timkelty** [comment]
@neoziro doing this optionally would be fine, but I'm still a bit confused why this would be happening.

If the mentioned file was changed between releases, rsync should replace it. No "merging" goes on.

**Comment by hachichaud** [comment]
@fundon we had the same issue : deleted files were copied from the previous release and were not removed by rsync.
It seems release 2.0.0 fixes this by using `--del` (https://github.com/shipitjs/shipit-deploy/pull/48/files#diff-e43940cc0a685e29518fb78bf84ec91dR69)

**Comment by timkelty** [comment]
@hachichaud that makes sense, but @fundon's example seems to describe the merging of file _contents_, which shouldn't be happening.

**Comment by fundon** [comment]
@hachichaud Thanks, I will try it.

**Comment by neoziro** [comment]
I close it because @timkelty is right, file merging is not done by rsync.
