### ISSUE TITLE
deploy/update.js : Copy previous release to release dir is actually copying release n-2

### ISSUE THREAD

**Issue by etienneCharignon** [shipitjs/shipit-deploy#66]
the task deploy/update.js is trying to copy the previous release if present. But actually it is taking two releases back for copy.

I suppose that this is due to the fact that "previous release" is the previous release of the current release but this task is actually creating a new release.

I've been trying to write a test to show that behaviors but did not managed to fin time.

**Comment by neoziro** [comment]
@etienneCharignon ho it's a bug, I think it's pretty easy to fix, I need to look at deeper. If you have time to write a test to show it, it will be a good thing.
