### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by tamtakoe** [shipitjs/shipit-deploy#72]
Deploy doesn't work in Windows. Problem with paths  to create an archive (extra slash at the beginning of the path. Problem in `path2` module). It doesn't work in PowerShell (it doesn't support `&&` command separator, only `;`). Problem with SCP command.

**Comment by grushikhin** [comment]
+1

**Comment by Jokero** [comment]
+1
Many frontend developers use Windows. So it's normal to deploy feature branches to staging environment from Windows

**Comment by vozovoz** [comment]
+1
u have to support this feature

**Comment by neoziro** [comment]
I have not any machine on Windows on my side, so if someone want to add the Windows support it's welcome.

**Comment by vlkosinov** [comment]
@tamtakoe you can try to use it under cygwin

**Comment by AntJanus** [comment]
hey guys,
I'm using Shipit and Shipit-deploy on a windows machine on a daily basis for about 6 months now.

What are the issues that everyone's seeing? I submitted a few PRs and fixed any Windows related bugs I've seen.

**Comment by tamtakoe** [comment]
@AntJanus for example, the problems that are described in the topic :-)

**Comment by AntJanus** [comment]
@tamtakoe right, I'm not having that issue. Can you post your `shipit-deploy` version and your error stack? I was fixing the pathing issue in [this PR](https://github.com/shipitjs/shipit-deploy/pull/53).

**Comment by jdat82** [comment]
@AntJanus: How do you use it on windows ? Shell commands are hardcoded in the code like "rm -rf ...". Maybe you are using cygwin or equivalent.

@neoziro: I think that's a conception issue. Not having windows is not blocking. Node being portable, that kind of operation should be done in pure node and not with shell commands. At least, you should write it in the readme to avoid people wasting time testing something that will never work.

**Comment by AntJanus** [comment]
@jdat82 ahhh, could be! I'm using CMDer which has a bunch of GNU tools loaded with it. I could help make it more portable by replacing `rm -rf` with stuff like `rimraf` which works cross system. 

@neoziro I can definitely try to make `shipit-deploy` more friendly to Windows; however, it'd definitely involve switching a few things out and using more external packages. If that's cool with you, I'll start submitting PRs as I come across stuff. If not, I wouldn't mind forking `shipit-deploy` and creating something like `shipit-deploy-windows`.

**Comment by neoziro** [comment]
I close it, if you can run it on windows @AntJanus it's OK, and I agree, feel free to create a module specially designed for Windows.
