### ISSUE TITLE
Add branch argument

### ISSUE THREAD

**Issue by Jokero** [shipitjs/shipit-deploy#73]
It's very common to deploy specific branch to environments (e.g., `feature` and `bug` branches to development and staging servers).

Example:
```
shipit staging deploy bug/someFix
```
or
```
shipit staging deploy --branch bug/someFix
shipit staging deploy -b bug/someFix
```

**Comment by neoziro** [comment]
Already answered, if you want to do that, you can use [minimist](https://www.npmjs.com/package/minimist).

```js
var argv = require('minimist')(process.argv.slice(2));
var branch = argv.branch;
```

**Comment by Jokero** [comment]
I use it:
```javascript
var args = minimist(process.argv.slice(2));

shipit.on('deploy', function() {
    if (args.b) {
        shipit.config.branch = args.b;
    }
});
```

Maybe it should be built-in feature?

**Comment by neoziro** [comment]
You can put it directly in shipit config, you don't need to set up it at deploy. It will not be a built-in feature, I prefer to let the choice to the user, it's two lines of code..
