### ISSUE TITLE
Attach shipit.* variables on global init

### ISSUE THREAD

**Issue by Sija** [shipitjs/shipit-deploy#74]
Otherwise it's not possible to use 'em from tasks invoked out of deploy cycle.
Example below:
```javascript
shipit.task('npm:build', function () {
  return shipit.remote('cd ' + path.join(shipit.releasesPath, shipit.releaseDirname) + ' && npm run build');
});
```
No way to run `shipit deploy npm:build` since `shipit.releasesPath` and friends are unset at that point.

**Comment by timkelty** [comment]
Agreed! Can you make PR?

**Comment by neoziro** [comment]
@Sija yes PR welcome
