### ISSUE TITLE
Rollback task should emit a event specifically for it when finished

### ISSUE THREAD

**Issue by thelinuxlich** [shipitjs/shipit-deploy#8]
So we could notify specifically when a rollback has finished

**Comment by neoziro** [comment]
I don't see in which case it is useful, do you have an example?

**Comment by thelinuxlich** [comment]
A simple case would be to notify "Rollback has finished..."

**Comment by neoziro** [comment]
You know when it's finished, you have "publish finished".

**Comment by thelinuxlich** [comment]
But it's generic, it could be a rollback or a normal deploy

**Comment by neoziro** [comment]
@thelinuxlich yes I know but you know what the command you just type, I mean I think it can be dangerous because when you rollback you want to exactly the same thing that when you deploy (restarting server, flush cache, etc...).
