### ISSUE TITLE
Add --tags to `git fetch -p`

### ISSUE THREAD

**Issue by janiv** [shipitjs/shipit-deploy#80]
The branch config option says that it accepts tags as well as branches or commit hashes. However, the git fetch command that runs does not pull down all tags which can result in a deploy failing. To esnure that git fetch pulls down all tags, the command should be modified to `git fetch -p --tags`.

**Comment by timkelty** [comment]
@janiv can you make a PR?

**Comment by janiv** [comment]
Yes, see #81.

**Comment by timkelty** [comment]
Looks good to me.
@neoziro can you merge and release?
