### ISSUE TITLE
TODO document the "key" option

### ISSUE THREAD

**Issue by Yvem** [shipitjs/shipit-deploy#87]
The shipitfile.js example references an undocumented `key` option.

Does it exist ? What does it do ?

**Comment by aglipanci** [comment]
@Yvem It seems to me like it does nothing. At least on the shipit-deploy repo there is no reference to any key variable anywhere.

**Comment by aglipanci** [comment]
@Yvem you can find this on the main repo: Path to SSH key

**Comment by neoziro** [comment]
Done
