### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by outrunthewolf** [shipitjs/shipit-deploy#9]
Do you have help for composer on a deploy. Specifically:

1. At what point in the flow should I run an composer install
2. Do I need to authorise my server keys against github for private repos or is there an interactive mode I can use?

Cheers

**Comment by neoziro** [comment]
You should run composer install locally (after "fetched") or remotely (after "updated"). Interactive mode is available (but only for commands starting with sudo, this problem will be solved in 2.0), but I think that the best option is to not have to use it.

**Comment by outrunthewolf** [comment]
but I think that the best option is to not have to use it
Thats kind of impossible for a complex modern day PHP project surely? The only way would be to include to vendor files in the repository which is not ideal.

I'll try some stuff out and see what sticks

**Comment by neoziro** [comment]
@outrunthewolf I talked about "interactive mode" not composer.

**Comment by outrunthewolf** [comment]
All sorted cheers
