### ISSUE TITLE
tests are not working

### ISSUE THREAD

**Issue by Yvem** [shipitjs/shipit-deploy#94]
Doing a fresh checkout, then
```bash
npm i
npm test
```

All tests are failing for `deploy:update task` and `pending:log task` (timeout)

Travis builds are not accessible for recent pull requests...

**Comment by Yvem** [comment]
found the cause : an uneeded mocking of clock(). PR coming soon.

**Comment by neoziro** [comment]
@Yvem if you can fix it thanks!

**Comment by neoziro** [comment]
Tests OK for me

**Comment by Yvem** [comment]
The usual programmer excuse ^^

tests are fixed in #96 (bump bluebird + finer clock mocking)

**Comment by neoziro** [comment]
@Yvem build is OK for master on Travis, I will not merge this PR because skipping fetch task is not the main use case
